@tool
extends Node2D


signal map_changed


# ============================================================================ #
#region Constants

# NOTE: These mapping straight-forward enough to be included as Dictionary
# constants here instead of being dynamically generated by looping through all
# tilesets, their sources, and the individual tiles - with the custom data layer
# set up for it. While the latter solution is arguably more scalable, it is not
# practical to invest so much development time into a project of such smaller
# scope.
const DEBUG_TILE_NAMES = {
    0: "_0",
    1: "_1",
    Vector2i.UP: "n",
    Vector2i.LEFT: "w",
    Vector2i.DOWN: "s",
    Vector2i.RIGHT: "e",
}
const SNAKE_HEAD_TILE_NAMES = {
    Vector2i.UP: "head_n",
    Vector2i.LEFT: "head_w",
    Vector2i.DOWN: "head_s",
    Vector2i.RIGHT: "head_e",
}
const SNAKE_BODY_EAT_TILE_NAME = "body_eat"
const WALL_TILE_NAME = "wall"
const FOOD_TILE_NAMES = {
    1: "food_small",
    2: "food_big",
}

#endregion
# ============================================================================ #


var _source_ids: Dictionary
var _tile_ids: Dictionary
var _terrain_ids: Dictionary


# ============================================================================ #
#region Godot builtins
func _ready() -> void:
    var children: Array[Node] = get_children()
    for child in children:
        if child is not TileMapLayer: continue

        var layer: TileMapLayer = child
        layer.connect("changed", func (): map_changed.emit())
        var tile_set: TileSet = layer.tile_set

        var layer_sources: Dictionary
        for source_index in range(tile_set.get_source_count()):
            var source_id: int = tile_set.get_source_id(source_index)
            var source: TileSetSource = tile_set.get_source(source_id)
            if source is not TileSetAtlasSource: continue

            # Populate _tile_ids
            var source_tiles: Dictionary
            for tile_index in range(source.get_tiles_count()):
                var atlas_coords: Vector2i = source.get_tile_id(tile_index)
                for alt_tile_index in range(
                        source.get_alternative_tiles_count(atlas_coords) + 1
                ):
                    var alt_tile_id: int = 0\
                            if alt_tile_index == 0\
                            else source.get_alternative_tile_id(
                                    atlas_coords, alt_tile_index - 1
                            )
                    var tile_name = source\
                            .get_tile_data(atlas_coords, alt_tile_id)\
                            .get_custom_data("tile_name") as StringName
                    if tile_name:
                        source_tiles[tile_name] = {
                            "coords": atlas_coords,
                            "alt_id": alt_tile_id
                        }
            _tile_ids[source_id] = source_tiles

            # Populate _source_ids
            layer_sources[source.resource_name] = source_id
        _source_ids[layer.name] = layer_sources

        # Populate _terrain_ids
        var layer_terrains: Dictionary
        for terrain_set_id in range(tile_set.get_terrain_sets_count()):
            for terrain_id in range(tile_set.get_terrains_count(terrain_set_id)):
                var terrain_name: String = tile_set.get_terrain_name(
                        terrain_set_id, terrain_id
                )
                assert(
                        terrain_name not in layer_terrains.keys(),
                        "Terrain name must be unique across terrain sets"
                )
                layer_terrains[terrain_name] = {
                    "terrain_set": terrain_set_id,
                    "terrain": terrain_id,
                }
        _terrain_ids[layer.name] = layer_terrains


    _source_ids.make_read_only()
    _tile_ids.make_read_only()
    _terrain_ids.make_read_only()
#endregion
# ============================================================================ #


# ============================================================================ #
#region Public methods

## Returns the [TileSetSource] ID of the [TileSet]s used in [param layer] given
## the [param source_name].
func get_source_id(layer: String, source_name: String) -> int:
    return _source_ids[layer][source_name]


## Returns the tile atlast coordinates of within the [param source_id], given
## its [param tile_name].
func get_tile_id(source_id: int, tile_name: StringName) -> Dictionary:
    return _tile_ids[source_id][tile_name]


## Returns the terrain ID given its [param layer] and [param terrain_name].
func get_terrain_id(layer: String, terrain_name: String) -> Dictionary:
    return _terrain_ids[layer][terrain_name]

#endregion
# ============================================================================ #
