name: "p0ng CI/CD"
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: p0ng
  PROJECT_PATH: p0ng

jobs:
  export-windows:
    name: Windows Export
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install build toolchain
        run: |
          choco install godot --version=${GODOT_VERSION}
          choco install rcedit
      - name: Download Export Templates
        run: |
          powershell -ExecutionPolicy Bypass -Command "& { New-Item -ItemType Directory -Force ($env:APPDATA)/Godot/export_templates }"
          $url = "https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_export_templates.tpz"
          $target = "${$env:APPDATA}\Godot_v${GODOT_VERSION}-stable_export_templates.tpz"
          Invoke-WebRequest -Uri $url -OutFile $target
          Expand-Archive -Path $target -DestinationPath ($env:APPDATA)/Godot/export_templates -Force
      - name: Windows Build
        run: |
          Set-Location $env:PROJECT_PATH
          mkdir -p -Force ./build/desktop_windows_x86_64
          godot.exe --headless --verbose --export-release "desktop_windows_x86_64" ./build/desktop_windows_x86_64/$env:EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: $env:EXPORT_NAME_desktop_windows_x86_64
          path: $env:PROJECT_PATH/build/desktop_windows_x86_64

  export-web:
    name: Web Export
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Install build toolchain
        run: |
          choco install godot --version=${GODOT_VERSION}
      - name: Download Export Templates
        run: |
          powershell -ExecutionPolicy Bypass -Command "& { New-Item -ItemType Directory -Force ($env:APPDATA)/Godot/export_templates }"
          $url = "https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_export_templates.tpz"
          $target = "${$env:APPDATA}\Godot_v${GODOT_VERSION}-stable_export_templates.tpz"
          Invoke-WebRequest -Uri $url -OutFile $target
          Expand-Archive -Path $target -DestinationPath ($env:APPDATA)/Godot/export_templates -Force
      - name: Web Build
        run: |
          Set-Location $env:PROJECT_PATH
          mkdir -p -Force ./build/web
          godot.exe --headless --verbose --export-release "web" ./build/web/$env:EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: $env:EXPORT_NAME_web
          path: $env:PROJECT_PATH/build/web
